name: "To Do: Create Issues"
on:   
  push:
    branches: [ master ]  
    #will trigger on pull request to the main branch, this will update all the todo issues if it has been cleared
  
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v2.4.1"
        id: "todo"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
